---
title: "Hawk-eye_data"
author: "Riku Komatani"
date: "2023-03-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(data.table)
```

```{r}
data17 <- read.csv("C:/Users/12244/STAT430/statcast/2017.csv")
data18 <- read.csv("C:/Users/12244/STAT430/statcast/2018.csv")
data19 <- read.csv("C:/Users/12244/STAT430/statcast/2019.csv")
data21 <- read.csv("C:/Users/12244/STAT430/statcast/2021.csv")
data22 <- read.csv("C:/Users/12244/STAT430/statcast/2022.csv")

sc <- rbind(data17, data18, data19, data21, data22)
```

```{r}
hawk_data <- read.csv("C:/Users/12244/OneDrive - University of Illinois - Urbana/ドキュメント/Baseball/Hawk-eye_data.csv")

player_hawk <- hawk_data %>%
  group_by(batter_name) %>%
  dplyr::summarise(count = n()) %>%
  arrange(desc(count))

head(player_hawk, 10)
```


```{r}
#Drop outliers for attack angle
get_batter_hawk <- function(batter) {
  batter_hawk <- hawk_data %>%
    filter(batter_name == batter,
         is_swing == 1)
  
  q1 = quantile(batter_hawk$sample_vert_attack_angle, 0.25)
  q3 = quantile(batter_hawk$sample_vert_attack_angle, 0.75)
  IQR = q3 - q1
  min_bound = q1 - 1.5 * IQR
  max_bound = q3 + 1.5 * IQR

  batter_hawk2 <- batter_hawk %>%
    filter(sample_vert_attack_angle >= min_bound & sample_vert_attack_angle <= max_bound)
  batter_hawk2
}

# betts_hawk <- get_batter_hawk("Betts, Mookie")
# altuve_hawk <- get_batter_hawk("Altuve, Jose")
bregman_hawk <- get_batter_hawk("Bregman, Alex")
# 
# smith_hawk <- hawk_data %>%
#   filter(batter_name == "Smith, Will")
# median(smith_hawk$sample_vert_attack_angle)
```

# Distribution of attack angle
```{r}
ggplot(bregman_hawk) + geom_histogram(aes(sample_vert_attack_angle))

# ggplot(betts_hawk) + geom_histogram(aes(sample_horiz_attack_angle))
sd(bregman_hawk$sample_vert_attack_angle)
summary(bregman_hawk$sample_vert_attack_angle)
```

# AA vs LA vs EV
```{r}
ggplot(bregman_hawk) + geom_point(aes(api_h_launch_angle, api_h_launch_speed, color = sample_vert_attack_angle))

# ggplot(hawk_data %>% filter(batter_name == 	
# "Smith, Will")) + geom_point(aes(sample_vert_attack_angle, api_h_launch_angle, color = api_h_launch_speed))

```
#########################################################################################################

```{r}
la_for_peak_ev_bound <- function(name, lower_la, upper_la) {
  batter <- name_converter(name)
  
  #Narrow data into Batter Name, Exit Velocity, and Launch Angle with non NA value
  test_data <- sc %>%
    filter(type == "X") %>%
    select(player_name, launch_speed, launch_angle) %>%
    na.omit() %>%
    filter(player_name == batter) %>%
    
    #Label data with launch angle for every bins of width 5 degrees
    mutate(theta5 = 5 * round(launch_angle / 5, 0)) %>%
    arrange(launch_angle)
  
  #Create data set of top 5 exit velocity within each bins
  new_df <- data.frame(theta5 = 0, top_10_ev = 0)

  for (theta in unique(test_data$theta5)) {
    n_data <- test_data %>% 
      filter(theta5 == theta)
    df <- data.frame(theta5 = theta, top_10_ev = quantile(n_data$launch_speed, seq(0, 1, 1/10))[10])
    new_df <- rbind(new_df, df)
  }

  new_df <- new_df[-c(1),]
  
  test_data <- inner_join(test_data, new_df, by = "theta5")

  top_10_data <- test_data %>%
    filter(launch_speed >= top_10_ev,
           launch_angle >= lower_la & launch_angle <= upper_la)
  
  #Create a quadratic regression for top 10 percent data
  top_10_data$launch_angle2 = top_10_data$launch_angle^2
  
  quadratic_fit <- lm(launch_speed ~ launch_angle + launch_angle2, data = top_10_data)

  #return launch angle that gives the max exit velocity and max exit velocity as a list
  return(list(top_10_data$launch_angle[which.max(predict(quadratic_fit))], max(predict(quadratic_fit))))
}
```

# Try different boundary angles
```{r}
la_for_peak_ev_possibilities <- function(batter) {
  d = data.frame("la_for_peak_ev" = c(0),
                 "ev" = c(0),
                 "lower_la" = c(0),
                 "upper_la" = c(0))
  
  d_table <- as.data.table(d)

  for (i in seq(-50, -20, 5)) {
    for (j in seq(20, 40, 5)) {
      d_j <- la_for_peak_ev_bound(batter, i, j)
      d_table <- rbind(d_table, list(d_j[[1]], d_j[[2]], i, j))
    }
  }
  d_table <- d_table[-1,]
  
  d_df <- as.data.frame(d_table)

  d_df
}
```
# Plot EV vs LA within boundary angles
```{r}
plot_ev_vs_la_bounds <- function(name, lower_la, upper_la) {
  batter <- name_converter(name)
  #Narrow data into Batter Name, Exit Velocity, and Launch Angle with non NA value
  data_batter <- sc %>%
    select(player_name, launch_speed, launch_angle) %>%
    na.omit() %>%
    #Label data with launch angle for every bins of width 5 degrees
    filter(player_name == batter) %>%
    mutate(theta5 = 5 * round(launch_angle / 5, 0)) %>%
    arrange(launch_angle)
  
  #Create data set of top 10 percent exit velocity within each bins
  new_df <- data.frame(theta5 = 0, top_10_ev = 0)
  
  for (theta in unique(data_batter$theta5)) {
    n_data <- data_batter %>% 
      filter(theta5 == theta)
    df <- data.frame(theta5 = theta, top_10_ev = quantile(n_data$launch_speed, seq(0, 1, 1/10))[10])
    new_df <- rbind(new_df, df)
  }

  new_df <- new_df[-c(1),]
  
  data_batter <- inner_join(data_batter, new_df, by = "theta5")
  
  top_10_data <- data_batter %>%
    filter(launch_speed >= top_10_ev,
           launch_angle >= lower_la & launch_angle <= upper_la) %>%
    mutate(top_10 = "Yes")
    
  #Join two data
  combined_data <- left_join(data_batter, top_10_data, by = c("player_name", "launch_speed", "launch_angle", "theta5")) %>%
    filter(launch_angle >= lower_la & launch_angle <= upper_la)
  
  #Indicate whether or not the exit velocity is in top 10 percent
  combined_data <- combined_data %>%
    mutate(top_10 = ifelse(is.na(top_10), "No", top_10))
  
  #Create a quadratic regression for top 10 percent data
  top_10_data$launch_angle2 = top_10_data$launch_angle^2
  
  quadratic_fit <- lm(launch_speed ~ launch_angle + launch_angle2, data = top_10_data)
  #Scatter plot data differentiating the top 10 percent points by color and indicating the maximum predicted value for the launch angle that gives the max exit velocity using the quadratic regression
  ggplot(combined_data) +
    geom_point(aes(launch_angle, launch_speed, color = top_10)) +
    scale_color_manual(values = c("red", "blue")) +
    stat_smooth(method = "lm", formula = y ~ x + I(x^2), data = top_10_data, aes(launch_angle, launch_speed), color = "black", se = FALSE) +
    geom_vline(aes(xintercept = top_10_data$launch_angle[which.max(predict(quadratic_fit))]), linetype = "dashed") +
    ggtitle(paste("Exit Velocity vs Launch Angle of", name)) +
    scale_x_continuous(name = "Launch Angle (deg)", breaks = seq(-40, 80, by = 10)) +
    scale_y_continuous(name = "Exit Velocity (mph)", breaks = seq(50, 120, by = 20)) +
    annotate(geom = "text", label = top_10_data$launch_angle[which.max(predict(quadratic_fit))], x = top_10_data$launch_angle[which.max(predict(quadratic_fit))], y = 50, vjust = 1)
}
```

```{r}
altuve_las <- la_for_peak_ev_possibilities("Altuve, Jose")
betts_las <- la_for_peak_ev_possibilities("Betts, Mookie")
bregman_las <- la_for_peak_ev_possibilities("Bregman, Alex")

Fletcher_las <- la_for_peak_ev_possibilities("Fletcher, David")
la_for_peak_ev_bound("Bregman, Alex", -15, 40)

la_for_peak_ev_bound("Zunino, Mike", -10, 40)
```
#########################################################################################################
```{r}
#Function to obtain the launch angle that gives the maximum exit velocity when using quadratic fit for all contacted balls
la_for_peak_ev_id <- function(id) {
  
  #Narrow data into Batter Name, Exit Velocity, and Launch Angle with non NA value. Filter to in-play.
  test_data <- sc %>%
    filter(type == "X") %>%
    select(player_name, batter, launch_speed, launch_angle) %>%
    na.omit() %>%
    filter(batter == id) %>%
    
  #Label data with launch angle for every bins of width 5 degrees
    mutate(theta5 = 5 * round(launch_angle / 5, 0)) %>%
    arrange(launch_angle)
  
  if (nrow(test_data) == 0) {
    return(list(NA, NA))
  }
  
  #Create data set of top 5 exit velocity within each bins
  new_df <- data.frame(theta5 = 0, top_10_ev = 0)

  for (theta in unique(test_data$theta5)) {
    n_data <- test_data %>% 
      filter(theta5 == theta)
    df <- data.frame(theta5 = theta, top_10_ev = quantile(n_data$launch_speed, seq(0, 1, 1/10))[10])
    new_df <- rbind(new_df, df)
  }

  new_df <- new_df[-c(1),]
  
  test_data <- inner_join(test_data, new_df, by = "theta5")

  top_10_data <- test_data %>%
    filter(launch_speed >= top_10_ev) %>%
    mutate(top_10 = "Yes")
  
  #Create a quadratic regression for top 10 percent data
  top_10_data$launch_angle2 = top_10_data$launch_angle^2
  
  quadratic_fit <- lm(launch_speed ~ launch_angle + launch_angle2, data = top_10_data)

  #return launch angle that gives the max exit velocity and max exit velocity as a list
  return(list(top_10_data$launch_angle[which.max(predict(quadratic_fit))], max(predict(quadratic_fit))))
}

```

# Order of AA vs Peak LA
```{r}
#For each player, find aa for avg ev, compare with avg la
# ~70 data points isn't enough to find peak la for max ev

df = data.frame("hitter" = " ",
                "batter_id" = c(0),
                "avg_ev" = c(0),
                "avg_la" = c(0),
                "avg_aa" = c(0),
                "peak_ev" = c(0),
                "peak_la" = c(0),
                "peak_aa" = c(0),
                "count" = c(0),
                "sd_aa" = c(0),
                "peak_la2" = c(0))
  
df_table <- as.data.table(df)

for (player in unique(hawk_data$batter_name)) {
  df_player <- hawk_data %>%
    filter(batter_name == player)
  hitter = df_player$batter_name[1]
  batter_id = df_player$player_at_bat[1]
  avg_ev = mean(df_player$api_h_launch_speed)
  avg_la = mean(df_player$api_h_launch_angle)
  avg_aa = mean(df_player$sample_vert_attack_angle)
  peak_ev = max(df_player$api_h_launch_speed)
  peak_la = df_player$api_h_launch_angle[which.max(df_player$api_h_launch_speed)]
  peak_aa = df_player$sample_vert_attack_angle[which.max(df_player$api_h_launch_speed)]
  sd_aa = sd(df_player$sample_vert_attack_angle)
  count = nrow(df_player)
  peak_la2 = la_for_peak_ev_id(batter_id)[[1]]
  
  df_table <- rbind(df_table, list(hitter, batter_id, avg_ev, avg_la, avg_aa, peak_ev, peak_la, peak_aa, count, sd_aa, peak_la2))
}

df_table = df_table[-1]

df_avg = as.data.frame(df_table) %>%
  filter(count >= 20) %>%
  arrange(desc(peak_aa)) 

#peak attack angle vs peak launch angle, both from hawk-eye
ggplot(df_avg) + geom_point(aes(avg_la, peak_la2))

ggplot(df_avg) + geom_point(aes(peak_la, peak_la2))
  
ggplot(df_avg) + geom_point(aes(avg_aa, peak_la2, color = avg_ev))

ggplot(df_avg) + geom_point(aes(peak_aa, peak_la2, color = peak_ev))
```
# Swing Speed vs Exit Velocity
```{r}
ggplot(hawk_data) + geom_point(aes(impact_point_speed_before_impact, api_h_launch_speed))

ggplot(hawk_data) + geom_point(aes(sweetspot_speed_before_impact, api_h_launch_speed))

```

# Verification of q
```{r}
# impact_point_speed_before_impact, impact_point_speed_after_impact, est_q, api_h_launch_speed, speed_ball_before_impact_x,y,z

# change units to ft/s
# Using v1, v2, V1, V2 to obtain q and e
hawk_data2 <- hawk_data %>%
  select(api_h_launch_speed, api_h_launch_angle, impact_from_centre_across_bat, impact_point_speed_before_impact, impact_point_speed_after_impact, impact_from_head, q_max, est_q, speed_ball_before_impact_x, speed_ball_before_impact_y, speed_ball_before_impact_z) %>%
  mutate(speed_ball_before_impact = sqrt(speed_ball_before_impact_x^2 + speed_ball_before_impact_y^2 + speed_ball_before_impact_z^2),
         #launch_speed = api_h_launch_speed * 5280 / (60 * 60),
         e = (api_h_launch_speed - impact_point_speed_after_impact) / (speed_ball_before_impact + impact_point_speed_before_impact),
         q = (api_h_launch_speed - impact_point_speed_before_impact) / (speed_ball_before_impact + impact_point_speed_before_impact))



```

```{r}
ggplot(hawk_data2) + geom_point(aes(impact_from_head, q), color = "red") + geom_point(aes(impact_from_head, e), color = "blue") + xlab("Distance from tip (inch)") + ylab("q and e")
```
# Using M_e, I_6, and m to calculate q
```{r}
# Typical 33in, 30 oz bat with CM located 20 in from the knob and I_cm = 3000 oz in^2
# Let axis of rotation = 6in from the knob
I_6 = 8880 #oz in^2
m = 5 #oz (mass of baseball)
# M_e = I_6 / (L - 6 - d)^2, L = 33in, d = distance from the tip of the barrel

hawk_data2 <- hawk_data2 %>%
  mutate(M_e = I_6 / (33 - 6 - impact_from_head)^2,
         # e_2 = 0.5,
         q_2 = (e - m / M_e) / (1 + m / M_e))

ggplot(hawk_data2) + geom_point(aes(impact_from_head, q_2))

```
# Making correction on q 
```{r}
hawk_data3 <- hawk_data2 %>%
  mutate(est_v2_based_on_est_q = (1 + est_q) * impact_point_speed_before_impact + est_q * speed_ball_before_impact)

ggplot(hawk_data2) + geom_point(aes(impact_from_head, est_q), color = "black") + geom_point(aes(impact_from_head, q), color = "red") + ylab("est_q and q") + xlab("Distance from tip (inch")

ggplot(hawk_data2) + geom_point(aes(impact_from_head, est_q), color = "black") + geom_point(aes(impact_from_head, q_2), color = "red") + ylab("est_q and q_2") + xlab("Distance from tip (inch)")
```

