---
title: "parse_retrosheet2_pbp"
output: html_document
date: '2022-06-11'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
getwd()
setwd("C:/Users/Riku/OneDrive - University of Illinois - Urbana/ドキュメント/R/baseballdatabank-master_2018-03-28/baseballdatabank-master/core")
library(tidyverse)
library(dplyr)
db <- src_sqlite("pitchRx.sqlite3", create = TRUE)

library(pitchRx)
files <- c("inning/inning_all.xml", "inning/inning_hit.xml", "miniscoreboard.xml", "players.xml")
scrape(start = "2008-01-01", end = "2008-01-30", connect = db$con)

```

```{r}
library(dplyr)
library(illinibaseball)
library(RMySQL)
library(randomForest)
library(caret)
library(rsample)
library(ggplot2)
library(gridExtra)
library(kableExtra)
library(tidyverse)
library(randomForest)
install.packages("metR")
library(metR)
filter_db = function(batter_name) {
  con = connect_db("uiuc")
  pitches = dbGetQuery(con, paste0("select * from fs_pitches where
                             batter_team = 'Illinois' and
                             batter_name = '", batter_name,"' and
                             season in (2019, 2020, 2021);"))
  dbDisconnect(con)
  return(pitches)
}
```

```{r}
data_Cam <- filter_db("Cam McDonald")
data_Cam$ball <- as.numeric(data_Cam$balls)
data_Cam$strike <- as.numeric(data_Cam$strikes)
data_Cam$count <- paste(data_Cam$ball, data_Cam$strike, sep = "-")

counts <- c("0-0", "0-2", "2-0")
swing <- c("Single", "Foul Ball", "Contact Out", "Swinging Strike", "Home Run", "Error", "Double", "Triple")
crcblue <- "#2905a1"

data_Cam <- data_Cam %>%
  mutate(swung = case_when(play_result %in% swing ~ 1, TRUE ~ 0))

first_Cam <- data_Cam %>%
  filter(count == "0-0")

k_zone_plot <- ggplot(data_Cam, aes(plate_x, plate_z)) +
  geom_segment(aes(x = -0.947, y = 3.6, xend = -0.947, yend = 1.5)) +
  geom_segment(aes(x = -0.947, y = 3.6, xend = 0.947, yend = 3.6)) + 
  geom_segment(aes(x = 0.947, y = 3.6, xend = 0.947, yend = 1.5)) + 
  geom_segment(aes(x = -0.947, y = 1.5, xend = 0.947, yend = 1.5)) +
  coord_equal() +
  scale_x_continuous("Horizontal location (ft.)",
                     limits = c(-2, 2)) +
  scale_y_continuous("Vertical location (ft.)",
                     limits = c(0, 5))
k_zone_plot +
  geom_point(aes(color = factor(swung))) +
  scale_color_manual("Swung", values = c("gray70", crcblue),
                     labels = c("No", "Yes"))

miggy_loess <- loess(swung ~ plate_x + plate_z, data = data_Cam,
                     control = loess.control(surface = "direct"))

pred_area <- expand.grid(plate_x = seq(-2, 2, by = 0.1),
                         plate_z = seq(0, 6, by = 0.1))
pred_area_fit <- pred_area %>%
  mutate(fit = as.numeric(predict(miggy_loess,
                                  newdata = .)))
cam_plot <- k_zone_plot %+%
  filter(pred_area_fit, fit >= 0, fit <= 1) +
  stat_contour(aes(z = fit, color = stat(level)),
               binwidth = 0.2) +
  scale_color_gradient(low = "white", high = crcblue) + 
  metR::geom_text_contour(aes(z = fit))

cam_plot <- cam_plot %>%
  directlabels::direct.label(method = "bottom.pieces")
cam_plot
count_dfs <- data_Cam %>%
  filter(count %in% counts) %>%
  split(pull(., count)) 

count_fits <- count_dfs %>%
  map(~loess(swung ~ plate_x + plate_z, data = .,
             control = loess.control(surface = "direct"))) %>%
  map(predict, new_data = pred_area) %>%
  map(~data.frame(fit = as.numeric(.))) %>%
  map_df(bind_cols, pred_area, .id = "count") %>%
  mutate(balls = str_sub(count, 1, 1),
         strikes = str_sub(count, 3, 3))
  
```


```{r}
data_Comia <- filter_db("Branden Comia")
data_Comia$ball <- as.numeric(data_Comia$balls)
data_Comia$strike <- as.numeric(data_Comia$strikes)
data_Comia$count <- paste(data_Comia$ball, data_Comia$strike, sep = "-")
data_Comia <- data_Comia %>%
  mutate(swung = case_when(play_result %in% swing ~ 1, TRUE ~ 0))

k_zone_plot <- ggplot(data_Comia, aes(plate_x, plate_z)) +
  geom_segment(aes(x = -0.947, y = 3.6, xend = -0.947, yend = 1.5)) +
  geom_segment(aes(x = -0.947, y = 3.6, xend = 0.947, yend = 3.6)) + 
  geom_segment(aes(x = 0.947, y = 3.6, xend = 0.947, yend = 1.5)) + 
  geom_segment(aes(x = -0.947, y = 1.5, xend = 0.947, yend = 1.5)) +
  coord_equal() +
  scale_x_continuous("Horizontal location (ft.)",
                     limits = c(-2, 2)) +
  scale_y_continuous("Vertical location (ft.)",
                     limits = c(0, 5))
k_zone_plot +
  geom_point(aes(color = factor(swung))) +
  scale_color_manual("Swung", values = c("gray70", crcblue),
                     labels = c("No", "Yes"))

miggy_loess <- loess(swung ~ plate_x + plate_z, data = data_Comia,
                     control = loess.control(surface = "direct"))

pred_area <- expand.grid(plate_x = seq(-2, 2, by = 0.1),
                         plate_z = seq(0, 6, by = 0.1))
pred_area_fit <- pred_area %>%
  mutate(fit = as.numeric(predict(miggy_loess,
                                  newdata = .)))
comia_plot <- k_zone_plot %+%
  filter(pred_area_fit, fit >= 0, fit <= 1) +
  stat_contour(aes(z = fit, color = stat(level)),
               binwidth = 0.2) +
  scale_color_gradient(low = "white", high = crcblue) + 
  metR::geom_text_contour(aes(z = fit))
comia_plot
cam_plot
```

